[package]
name = "aoc23_08"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc_utils = { path = "../aoc_utils" }
nom = "7.1.3"
num = "0.4.1"
