[package]
name = "aoc22_11"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc_utils = { path = "../aoc_utils" }
lazy_static = "1.4.0"
regex = "1.7.0"
num-integer = "0.1.45"
